# Generated by Django 3.1.3 on 2020-12-02 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
