# Generated by Django 3.1.3 on 2020-12-02 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_otherincome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='otherincome',
            new_name='Otherincomee',
        ),
    ]
